import React, { createContext, useContext, useState, useEffect } from 'react';

type Language = 'en' | 'pt';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string, fallback?: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  en: {
    // Navigation
    'nav.experience': 'The Experience',
    'nav.locations': 'Locations',
    'nav.pricing': 'Pricing',
    'nav.flightdeck': 'Flight Deck',
    'nav.booknow': 'BOOK NOW',
    
    // Hero
    'hero.title1': 'EFOIL OVER THE',
    'hero.title2': 'ALGARVE.',
    'hero.subtitle': 'A unique way to experience nature in the Ría Formosa. Glide over crystal waters with our zero-emission electric hydrofoils.',
    'hero.btn': 'SECURE YOUR SESSION',
    
    // Pricing
    'pricing.starter.title': 'Starter Flight (For 2 or 3)',
    'pricing.starter.desc': '20 min Instruction Session each',
    'pricing.half.title': 'Half Experience (For 2)',
    'pricing.half.desc': '30 min Glide each',
    'pricing.full.title': 'Full Experience (Solo)',
    'pricing.full.desc': '1h Solo Session',
    'pricing.popular': 'MOST POPULAR',
    
    // Booking and Experience Section
    'exp.title1': 'THE ',
    'exp.title2': 'EXPERIENCE',
    'exp.subtitle': 'Everything you need to fly above the water safely and effortlessly.',
    'exp.grid1.title': 'BREATHTAKING LOCATIONS',
    'exp.grid1.desc': 'Available across the stunning Ria Formosa and East Algarve coast.',
    'exp.grid2.title': 'GIFT VOUCHERS AVAILABLE!',
    'exp.grid2.desc1': 'Give the gift of flight & fun. ',
    'exp.grid2.desc2': 'Purchase at checkout!',
    'exp.grid3.title': 'QUALIFIED INSTRUCTOR',
    'exp.grid3.desc': 'Full safety briefing, demonstration and instruction on how to operate the eFoil + Controller.',
    'exp.grid4.title': 'SAFETY EQUIPMENT',
    'exp.grid4.desc1': 'Life jackets and helmets to ensure safety on the water. ',
    'exp.grid4.desc2': 'Full public liability + accident insurance included. ',
    'exp.grid4.desc3': 'Wetsuits available!',
    'pricing.starter.longDesc': 'Learn the basics together: how to handle the e-foil, balance, and get on the board safely. Take turns sharing the session with a partner.',
    'pricing.half.longDesc': 'Get a true taste of the flight with a partner. Take turns on the board to experience the thrill of gliding above the water.',
    'pricing.full.longDesc': 'The ultimate solo adventure. Embark on a scenic route, master your turns, and enjoy the e-foiling experience to the absolute max for a full hour to yourself.',
    'booking.title1': 'SECURE YOUR ',
    'booking.title2': 'SESSION',
    'booking.name': 'Full Name',
    'booking.email': 'Email Address',
    'booking.phone': 'Phone Number',
    'booking.date': 'Select Date',
    'booking.time': 'Session Time',
    'booking.checking': 'Checking availability...',
    'booking.selectSession': 'Select a session',
    'booking.morning': 'Morning (10:00 - 13:00)',
    'booking.evening': 'Evening (15:00 - 18:00)',
    'booking.bookedOut': '- Fully Booked',
    'booking.location': 'Select Location',
    'booking.type': 'Experience Type',
    'booking.paymentInfo': 'Payment is done on site',
    'booking.paymentInfo2': ', or on the day of the ride.',
    'booking.weatherInfo': 'Times and locations may vary depending on weather and tide conditions.',
    'booking.waiver1': 'I agree to the ',
    'booking.waiverLink': 'Digital Waiver & Liability Form',
    'booking.waiver2': ' and confirm I am able to swim.',
    'loc.title': 'Choose Your Flight Zone',
    'loc.subtitle': 'Discover the most pristine waters in the Algarve, handpicked for the perfect e-foil experience.',

    // Common
    'common.comingSoon': 'Coming Soon',
    'common.bookOnline': 'Or book online',
    'common.contactUs': 'Contact us directly to book, or use the form below.',
    'common.secureSession': 'SECURE YOUR SESSION',
    'common.bookThisFlight': 'Book this flight',
    'common.confirmBooking': 'CONFIRM BOOKING',
    'common.book': 'Book',
    
    // Login
    'login.title': 'Access Flight Deck',
    'login.subtitle': 'Enter your booking email or phone number to access your Flight Deck.',
    'login.email': 'Email',
    'login.phone': 'Phone Number',
    'login.emailLabel': 'Email Address',
    'login.phoneLabel': 'Phone Number',
    'login.submit': 'LOG IN',
    'login.book': 'BOOK A SESSION',
    'login.error': 'No reservation found with this ',
    'login.error2': 'An error occurred while looking up your reservation.',
    'login.placeholderEmail': 'john@example.com',
    'login.placeholderPhone': '+1 234 567 890',
    
    // Welcome / Dashboard Checks
    'welcome.title': 'WELCOME TO FLIGHT SCHOOL',
    'welcome.subtitle': 'Please complete your pre-flight checks before your session.',
    'dashboard.loading': 'Loading Flight Deck...',
    'dashboard.title': 'Flight Deck',
    'dashboard.signOut': 'Sign Out',
    'dashboard.thanks': 'Thanks for reserving',
    'dashboard.statusLine': 'Your flight status',
    'dashboard.wind': 'Wind Speed',
    'dashboard.knots': 'knots',
    'dashboard.optimal': 'Optimal for eFoiling',
    'dashboard.waterTemp': 'Water Temp',
    'dashboard.comfortable': 'Comfortable',
    'dashboard.tide': 'Tide Status',
    'dashboard.launchSpot': 'Launch Spot',
    'dashboard.openMaps': 'OPEN IN MAPS',
    'dashboard.bookingDetails': 'Booking Details',
    'dashboard.name': 'Full Name',
    'dashboard.email': 'Email',
    'dashboard.phone': 'Phone',
    'dashboard.dateTime': 'Date & Time',
    'dashboard.location': 'Location',
    'dashboard.time': 'Session Time',
    'dashboard.experience': 'Experience',
    'dashboard.wetsuitReq': 'Select your size (Please request 24h in advance)',
    'dashboard.noWetsuit': 'No Wetsuit',
    'dashboard.size': 'Size',
    'dashboard.status': 'FLIGHT STATUS',
    'check.physical': 'PHYSICAL CONDITION',
    'check.waiver': 'LIABILITY WAIVER',
    'check.experience': 'EXPERIENCE LEVEL',
    'check.wetsuit': 'WETSUIT SIZE',
    'check.cleared': 'CLEARED',
    'check.pending': 'PENDING',
    'check.select': 'SELECT',
    'check.review': 'REVIEW WAIVER',
    'check.confirm': 'CONFIRM HEALTH',
    'flightSchool.title': 'FLIGHT SCHOOL',
    'flightSchool.briefing': 'SAFETY BRIEFING',
    'dashboard.gearProfile': 'Gear & Profile',
    'check.healthReq': 'Health check required',
    'check.greenLight': 'Green Light',
    'check.completeCheck': 'Complete Check',
    'check.waiverDesc': 'Digital liability form',
    'check.signed': 'SIGNED',
    'check.reviewSign': 'Review & Sign',
    'check.experienceDesc': 'Help us tailor your session',
    'check.logged': 'LOGGED',
    'check.setExperience': 'Set Experience',
    'dashboard.flightSchool': 'Flight School',
    'dashboard.checklistTitle': 'Safety Briefing Checklist',
    'dashboard.checklistDesc': 'Please review the video and check off the following before you arrive.',
    'check.q1': 'I understand that I have to stay clear of swimmers or any obstacle in a 100m distance.',
    'check.q2': 'I know how to fall safely (away from the board and foil).',
    'check.q3': 'I understand how to release the throttle immediately if I lose balance.',
    'dashboard.gallery': 'After-Flight Gallery',
    'dashboard.mediaTitle': 'Cloud Folder: Your Session Media',
    'dashboard.mediaDesc': 'Return here after your flight to find the link to your GoPro footage and drone shots.',
    'dashboard.availPost': 'AVAILABLE POST-FLIGHT',
    'health.title': 'Health Declaration',
    'health.desc': 'To ensure your safety during the eFoil experience, please confirm the following:',
    'health.q1': 'I do not have any severe heart conditions or cardiovascular issues.',
    'health.q2': 'I am not currently pregnant.',
    'health.q3': 'I do not have any back, neck, or joint injuries that could be aggravated by falling into water.',
    'health.q4': 'I am a capable swimmer and comfortable in open water.',
    'health.q5': 'I am not under the influence of alcohol or drugs.',
    'health.cancel': 'Cancel',
    'health.confirm': 'I Confirm I am Fit',
    'waiver.agreeSign': 'I Agree & Sign',
    'waiver.p7Confirm': 'By clicking "I Agree & Sign", I acknowledge that I have read this document in its entirety and fully understand its terms.',
    'expModal.title': 'Experience Level',
    'expModal.desc': 'Have you ever surfed, foiled, or used an eFoil before? Select the option that best describes your experience.',
    'expModal.opt1': 'Never - Complete Beginner',
    'expModal.opt2': 'I have surfed or wakeboarded',
    'expModal.opt3': 'I have foiled (kite/wing/surf)',
    'expModal.opt4': 'I have used an eFoil before',
    'expModal.save': 'Save Experience',
    
    // Locations
    'loc.beliche.name': 'Beliche Lake',
    'loc.beliche.desc': 'Freshwater perfection / Smooth, glassy conditions surrounded by nature. Perfect for beginners.',
    'loc.fuseta.name': 'Fuseta',
    'loc.fuseta.desc': 'Golden sands & open horizon for long glides.',
    'loc.cabanas.name': 'Cabanas de Tavira',
    'loc.cabanas.desc': 'Home Base / Crystal Calm waters.',
    'loc.altura.name': 'Altura',
    'loc.altura.desc': 'Wide open bays perfect for cruising and carving.',
    'loc.cross.name': 'The Cross-Border Special',
    'loc.cross.desc': 'Vila Real to Isla Cristina (Spain). A unique international flight.',
    
    // Footer
    'footer.contact': 'Contact',
    'footer.privacy': 'Privacy Policy',
    'footer.terms': 'Terms of Service',
    'footer.desc': 'The ultimate noise-free, zero-emission electric hydrofoil experience in the Algarve.',
    'footer.quickLinks': 'Quick Links',
    'footer.faq': 'FAQ',
    'footer.admin': 'Admin',
    'footer.hq': 'FlyFoil Formosa HQ',
    'footer.location': 'Ria Formosa, Portugal',
    'footer.copyright': 'FLYFOILFORMOSA.COM. FlyFoil Formosa is operated in partnership with Altura Kite (RNAAT 981/2017).',

    // Mobile Nav
    'nav.home': 'Home',
    'social.title': 'Social Media',
    'social.subtitle': "See what it's like to fly with us.",
    'social.follow': 'Follow Us',
    'nav.map': 'Map',
    'nav.profile': 'Profile',
    
    // Waiver
    'waiver.title': 'Liability Waiver',
    'waiver.close': 'Close',
    'waiver.p1': 'RELEASE OF LIABILITY, WAIVER OF CLAIMS, EXPRESS ASSUMPTION OF RISK AND INDEMNITY AGREEMENT',
    'waiver.p2': 'Please read and be certain you understand the implications of signing.',
    'waiver.p3': '1. I understand that eFoiling involves inherent risks, including but not limited to: falling into water, impact with the board or foil, marine life encounters, and varying weather/water conditions.',
    'waiver.p4': '2. I agree to wear the provided personal flotation device (PFD) and helmet at all times while on the water.',
    'waiver.p5': '3. I agree to follow all instructions provided by the instructor and acknowledge that failure to do so may result in the immediate termination of my session without refund.',
    'waiver.p6': '4. I hereby release, waive, and discharge FlyFoil, its instructors, and affiliates from any and all liability, claims, demands, or causes of action arising out of any damage, loss, or injury to me or my property.',
    'waiver.p7': 'By clicking "Close", I acknowledge that I have read this document in its entirety and fully understand its terms.',

    // FAQ
    'faq.title': 'Got Questions?',
    'faq.subtitle': 'Everything you need to know before your flight.',
    'faq1.q': 'Is it difficult?',
    'faq1.a': "Think of it like riding a bike—it takes a little balance at first, but once you get it, it's magical. 'Taxiing' on your knees is fun and achievable in 10-20 mins. And remember, falling into the water is part of the adventure!",
    'faq2.q': 'Do I need to be an athlete?',
    'faq2.a': 'Not at all! If you can stand up from a kneeling position, you can eFoil. Our boards are designed for stability and our instructors guide you at your own pace.',
    'faq3.q': 'What should I bring?',
    'faq3.a': 'Just bring swimwear, a towel, and sunscreen. We provide the eFoil, helmet, life jacket, and wetsuit (if needed).',
    'faq4.q': 'Is it safe for the Ria Formosa environment?',
    'faq4.a': 'Absolutely. Our eFoils use 100% electric, silent motors. There are no emissions, no wake to disturb the shoreline, and no noise pollution, making it perfectly safe for the local marine life.',
    'faq5.q': 'What is the minimum age?',
    'faq5.a': 'Riders must be at least 12 years old. Anyone under 18 needs a parent or guardian present to sign the digital waiver.',
  },
  pt: {
    // Navigation
    'nav.experience': 'A Experiência',
    'nav.locations': 'Localizações',
    'nav.pricing': 'Preçário',
    'nav.flightdeck': 'Área de Cliente',
    'nav.booknow': 'RESERVAR',
    
    // Hero
    'hero.title1': 'EFOIL NO',
    'hero.title2': 'ALGARVE.',
    'hero.subtitle': 'Uma forma única de viver a natureza na Ria Formosa. Deslize sobre águas cristalinas com as nossas pranchas elétricas.',
    'hero.btn': 'GARANTA A SUA SESSÃO',
    
    // Pricing
    'pricing.starter.title': 'Voo de Iniciação (Para 2 ou 3)',
    'pricing.starter.desc': 'Sessão de Instrução de 20 min cada',
    'pricing.half.title': 'Meia Experiência (Para 2)',
    'pricing.half.desc': 'Deslize de 30 min cada',
    'pricing.full.title': 'Experiência Completa (Individual)',
    'pricing.full.desc': 'Sessão Individual de 1h',
    'pricing.popular': 'MAIS POPULAR',
    
    // Booking and Experience Section
    'exp.title1': 'A ',
    'exp.title2': 'EXPERIÊNCIA',
    'exp.subtitle': 'Tudo o que precisa para voar sobre a água com segurança e sem esforço.',
    'exp.grid1.title': 'LOCALIZAÇÕES DESLUMBRANTES',
    'exp.grid1.desc': 'Disponível em toda a deslumbrante Ria Formosa e costa do Sotavento Algarvio.',
    'exp.grid2.title': 'VOUCHERS DE OFERTA!',
    'exp.grid2.desc1': 'Ofereça o dom do voo e diversão. ',
    'exp.grid2.desc2': 'Compre no checkout!',
    'exp.grid3.title': 'INSTRUTOR QUALIFICADO',
    'exp.grid3.desc': 'Briefing completo de segurança, demonstração e instrução sobre como operar a eFoil + Comando.',
    'exp.grid4.title': 'EQUIPAMENTO DE SEGURANÇA',
    'exp.grid4.desc1': 'Coletes salva-vidas e capacetes para garantir segurança. ',
    'exp.grid4.desc2': 'Seguro de responsabilidade civil e acidentes incluído. ',
    'exp.grid4.desc3': 'Fatos de surf disponíveis!',
    'pricing.starter.longDesc': 'Aprendam as bases juntos: como manusear a prancha, equilíbrio e posicionamento seguro. Revezem-se desfrutando da sessão a dois.',
    'pricing.half.longDesc': 'Tenham o verdadeiro gosto do voo com um parceiro. Revezem-se na prancha para vivenciar a emoção de deslizar sobre a água.',
    'pricing.full.longDesc': 'A derradeira aventura a solo. Embarque numa rota cénica, domine as curvas e desfrute ao máximo por uma hora inteira só para si.',
    'booking.title1': 'GARANTA A SUA ',
    'booking.title2': 'SESSÃO',
    'booking.name': 'Nome Completo',
    'booking.email': 'Email',
    'booking.phone': 'Telemóvel',
    'booking.date': 'Selecionar Data',
    'booking.time': 'Hora da Sessão',
    'booking.checking': 'A verificar disponibilidade...',
    'booking.selectSession': 'Selecione uma sessão',
    'booking.morning': 'Manhã (10:00 - 13:00)',
    'booking.evening': 'Tarde (15:00 - 18:00)',
    'booking.bookedOut': '- Esgotado',
    'booking.location': 'Selecionar Localização',
    'booking.type': 'Tipo de Experiência',
    'booking.paymentInfo': 'O pagamento é efetuado no local',
    'booking.paymentInfo2': ', ou no dia da atividade.',
    'booking.weatherInfo': 'Os horários e locais podem variar dependendo das condições meteorológicas/marés.',
    'booking.waiver1': 'Concordo com o ',
    'booking.waiverLink': 'Termo de Responsabilidade Digital',
    'booking.waiver2': ' e confirmo que sei nadar.',
    'loc.title': 'Escolha a sua Zona de Voo',
    'loc.subtitle': 'Descubra as águas mais cristalinas do Algarve, escolhidas para a experiência eFoil perfeita.',

    // Common
    'common.comingSoon': 'Em Breve',
    'common.bookOnline': 'Ou reserve online',
    'common.contactUs': 'Contacte-nos diretamente para reservar, ou use o formulário abaixo.',
    'common.secureSession': 'GARANTA A SUA SESSÃO',
    'common.bookThisFlight': 'Reservar este voo',
    'common.confirmBooking': 'CONFIRMAR RESERVA',
    'common.book': 'Reservar',
    
    // Login
    'login.title': 'Acesso à Área de Cliente',
    'login.subtitle': 'Insira o seu email de reserva ou telemóvel para aceder.',
    'login.email': 'Email',
    'login.phone': 'Telemóvel',
    'login.emailLabel': 'Endereço de Email',
    'login.phoneLabel': 'Número de Telemóvel',
    'login.submit': 'ENTRAR',
    'login.book': 'RESERVAR UMA SESSÃO',
    'login.error': 'Não foi encontrada nenhuma reserva com este ',
    'login.error2': 'Ocorreu um erro ao procurar a sua reserva.',
    'login.placeholderEmail': 'joao@exemplo.pt',
    'login.placeholderPhone': '+351 912 345 678',

    // Welcome / Dashboard Checks
    'welcome.title': 'BEM-VINDO À ESCOLA DE VOO',
    'welcome.subtitle': 'Por favor, complete as suas verificações pré-voo antes da sua sessão.',
    'dashboard.loading': 'A Carregar a Área de Cliente...',
    'dashboard.title': 'Área de Cliente',
    'dashboard.signOut': 'Sair',
    'dashboard.thanks': 'Obrigado por reservar',
    'dashboard.statusLine': 'Estado do seu voo',
    'dashboard.wind': 'Velocidade do Vento',
    'dashboard.knots': 'nós',
    'dashboard.optimal': 'Ideal para eFoil',
    'dashboard.waterTemp': 'Temp. da Água',
    'dashboard.comfortable': 'Agradável',
    'dashboard.tide': 'Estado da Maré',
    'dashboard.launchSpot': 'Local de Partida',
    'dashboard.openMaps': 'ABRIR NO MAPA',
    'dashboard.bookingDetails': 'Detalhes da Reserva',
    'dashboard.name': 'Nome Completo',
    'dashboard.email': 'Email',
    'dashboard.phone': 'Telemóvel',
    'dashboard.dateTime': 'Data e Hora',
    'dashboard.location': 'Localização',
    'dashboard.time': 'Hora da Sessão',
    'dashboard.experience': 'Experiência',
    'dashboard.wetsuitReq': 'Selecione o tamanho (Pedir com 24h de antecedência)',
    'dashboard.noWetsuit': 'Sem Fato',
    'dashboard.size': 'Tamanho',
    'dashboard.status': 'ESTADO DO VOO',
    'check.physical': 'CONDIÇÃO FÍSICA',
    'check.waiver': 'TERMO DE RESPONSABILIDADE',
    'check.experience': 'NÍVEL DE EXPERIÊNCIA',
    'check.wetsuit': 'TAMANHO DO FATO DE SURF',
    'check.cleared': 'APROVADO',
    'check.pending': 'PENDENTE',
    'check.select': 'SELECIONAR',
    'check.review': 'REVER TERMO',
    'check.confirm': 'CONFIRMAR SAÚDE',
    'flightSchool.title': 'ESCOLA DE VOO',
    'flightSchool.briefing': 'BRIEFING DE SEGURANÇA',
    'dashboard.gearProfile': 'Equipamento e Perfil',
    'check.healthReq': 'Verificação de saúde necessária',
    'check.greenLight': 'Luz Verde',
    'check.completeCheck': 'Completar Verificação',
    'check.waiverDesc': 'Termo de responsabilidade digital',
    'check.signed': 'ASSINADO',
    'check.reviewSign': 'Rever e Assinar',
    'check.experienceDesc': 'Ajude-nos a adaptar a sua sessão',
    'check.logged': 'REGISTADO',
    'check.setExperience': 'Definir Experiência',
    'dashboard.flightSchool': 'Escola de Voo',
    'dashboard.checklistTitle': 'Lista de Verificação de Segurança',
    'dashboard.checklistDesc': 'Reveja o vídeo e marque os itens abaixo antes de chegar.',
    'check.q1': 'Compreendo que devo manter 100m de distância de banhistas ou de qualquer obstáculo.',
    'check.q2': 'Sei como cair em segurança (afastado da prancha e do foil).',
    'check.q3': 'Compreendo como largar o acelerador imediatamente se perder o equilíbrio.',
    'dashboard.gallery': 'Galeria Pós-Voo',
    'dashboard.mediaTitle': 'Pasta Cloud: Multimédia da sua Sessão',
    'dashboard.mediaDesc': 'Regresse aqui após o voo para encontrar as fotografias e vídeos do seu voo.',
    'dashboard.availPost': 'DISPONÍVEL APÓS O VOO',
    'health.title': 'Declaração de Saúde',
    'health.desc': 'Para garantir a sua segurança durante a experiência de eFoil, por favor confirme o seguinte:',
    'health.q1': 'Não tenho problemas cardíacos graves ou cardiovasculares.',
    'health.q2': 'Não estou grávida.',
    'health.q3': 'Não tenho lesões nas costas, pescoço ou articulações que possam ser agravadas ao cair na água.',
    'health.q4': 'Sei nadar bem e sinto-me confortável em águas abertas.',
    'health.q5': 'Não me encontro sob o efeito de álcool ou drogas.',
    'health.cancel': 'Cancelar',
    'health.confirm': 'Confirmo que estou apto',
    'waiver.agreeSign': 'Concordo e Assino',
    'waiver.p7Confirm': 'Ao clicar em "Concordo e Assino", reconheço que li este documento na íntegra e compreendo totalmente os seus termos.',
    'expModal.title': 'Nível de Experiência',
    'expModal.desc': 'Já fez surf, foil ou usou um eFoil antes? Selecione a opção que melhor descreve a sua experiência.',
    'expModal.opt1': 'Nunca - Iniciante completo',
    'expModal.opt2': 'Já fiz surf ou wakeboard',
    'expModal.opt3': 'Já fiz foil (kite/wing/surf)',
    'expModal.opt4': 'Já usei um eFoil antes',
    'expModal.save': 'Guardar Experiência',
    
    // Locations
    'loc.beliche.name': 'Lago do Beliche',
    'loc.beliche.desc': 'Perfeição em água doce / Condições suaves e tranquilas rodeadas de natureza. Perfeito para iniciantes.',
    'loc.fuseta.name': 'Fuseta',
    'loc.fuseta.desc': 'Areias douradas e horizonte aberto para longos deslizes.',
    'loc.cabanas.name': 'Cabanas de Tavira',
    'loc.cabanas.desc': 'Base Principal / Águas cristalinas e calmas.',
    'loc.altura.name': 'Altura',
    'loc.altura.desc': 'Baías amplas e abertas perfeitas para cruzeiros e manobras.',
    'loc.cross.name': 'Especial Fronteiriço',
    'loc.cross.desc': 'Vila Real a Isla Cristina (Espanha). Um voo internacional único.',
    
    // Footer
    'footer.contact': 'Contacto',
    'footer.privacy': 'Política de Privacidade',
    'footer.terms': 'Termos de Serviço',
    'footer.desc': 'A melhor experiência de hydrofoil elétrico sem emissões e sem ruído no Algarve.',
    'footer.quickLinks': 'Links Rápidos',
    'footer.faq': 'Perguntas Frequentes',
    'footer.admin': 'Administração',
    'footer.hq': 'Sede FlyFoil Formosa',
    'footer.location': 'Ria Formosa, Portugal',
    'footer.copyright': 'FLYFOILFORMOSA.COM. A FlyFoil Formosa opera em parceria com a Altura Kite (RNAAT 981/2017).',

    // Mobile Nav
    'nav.home': 'Início',
    'social.title': 'Redes Sociais',
    'social.subtitle': 'Veja como é voar connosco.',
    'social.follow': 'Siga-nos',
    'nav.map': 'Mapa',
    'nav.profile': 'Perfil',
    
    // Waiver
    'waiver.title': 'Termo de Responsabilidade',
    'waiver.close': 'Fechar',
    'waiver.p1': 'LIBERAÇÃO DE RESPONSABILIDADE, RENÚNCIA DE RECLAMAÇÕES, PRESSUPOSIÇÃO EXPRESSA DE RISCO E ACORDO DE INDEMNIZAÇÃO',
    'waiver.p2': 'Por favor leia e certifique-se que compreende as implicações de assinar.',
    'waiver.p3': '1. Entendo que o eFoiling envolve riscos inerentes, incluindo mas não se limitando a: cair na água, impacto com a prancha ou foil, encontros com vida marinha e condições variáveis de tempo/água.',
    'waiver.p4': '2. Concordo em usar o colete salva-vidas (PFD) fornecido e o capacete em todos os momentos enquanto estiver na água.',
    'waiver.p5': '3. Concordo em seguir todas as instruções fornecidas pelo instrutor e reconheço que a não conformidade pode resultar na rescisão imediata da minha sessão sem reembolso.',
    'waiver.p6': '4. Por este meio, liberto, renuncio e desobrigo a FlyFoil, os seus instrutores e associados de toda e qualquer responsabilidade, reclamações, exigências ou causas de ação decorrentes de qualquer dano, perda ou lesão em mim ou na minha propriedade.',
    'waiver.p7': 'Ao clicar em "Fechar", reconheço que li este documento na íntegra e compreendo totalmente os seus termos.',

    // FAQ
    'faq.title': 'Tem Dúvidas?',
    'faq.subtitle': 'Tudo o que precisa de saber antes do seu voo.',
    'faq1.q': 'É difícil?',
    'faq1.a': "Pense nisto como andar de bicicleta—exige um pouco de equilíbrio no início, mas assim que apanha o jeito, é mágico. Andar de joelhos é divertido e alcançável em 10-20 mins. E lembre-se, cair à água faz parte da aventura!",
    'faq2.q': 'Preciso de ser um atleta?',
    'faq2.a': 'De modo algum! Se consegue levantar-se de uma posição de joelhos, consegue andar de eFoil. As nossas pranchas são concebidas para estabilidade e os nossos instrutores acompanham-no ao seu próprio ritmo.',
    'faq3.q': 'O que devo levar?',
    'faq3.a': 'Traga apenas fato de banho, uma toalha e protetor solar. Nós fornecemos a eFoil, capacete, colete salva-vidas e fato de surf (se necessário).',
    'faq4.q': 'É seguro para o ambiente da Ria Formosa?',
    'faq4.a': 'Absolutamente. As nossas eFoils usam motores 100% elétricos e silenciosos. Não há emissões, não há ondulação para perturbar a costa e não há poluição sonora, tornando-a perfeitamente segura para a vida marinha local.',
    'faq5.q': 'Qual é a idade mínima?',
    'faq5.a': 'Os participantes devem ter pelo menos 12 anos. Menores de 18 anos precisam da presença de um pai ou responsável para assinar o termo de responsabilidade digital.',
  }
};

const LanguageContext = createContext<LanguageContextType>({
  language: 'en',
  setLanguage: () => {},
  t: (key, fallback) => fallback || key,
});

export const LanguageProvider = ({ children }: { children: React.ReactNode }) => {
  const [language, setLanguage] = useState<Language>(() => {
    const saved = localStorage.getItem('language');
    return (saved as Language) || 'en';
  });

  useEffect(() => {
    localStorage.setItem('language', language);
    document.documentElement.lang = language;
  }, [language]);

  const t = (key: string, fallback?: string) => {
    return translations[language][key] || fallback || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => useContext(LanguageContext);
